### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IrangaSupunAthukorale** [izmailoff/mqtt-mongo#1]
Hello Izmailoff,

I am not a Java Programmer, so not sure if this is a generic Java issue. I have downloaded, compiled and tried to run the jar file. However, get the following error.
# java -jar mqtt-mongo-assembly-0.1.jar

02:40:20,638 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
02:40:20,638 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
02:40:20,638 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/supun/iot/mqtt-mongo-master/target/scala-2.11/mqtt-mongo-assembly-0.1.jar!/logback.xml]
02:40:20,662 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@73946e71 - URL [jar:file:/home/supun/iot/mqtt-mongo-master/target/scala-2.11/mqtt-mongo-assembly-0.1.jar!/logback.xml] is not of type file
02:40:20,742 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
02:40:20,746 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
02:40:20,835 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.sandinh.paho.akka.MqttPubSub] to INFO
02:40:20,836 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to INFO
02:40:20,836 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
02:40:20,837 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
02:40:20,840 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@77e994ed - Registering current configuration as safe fallback point
[INFO] [12/26/2015 02:40:21.530] [main] [ActorSystem(mqtt-mongo-system)] 

---

|  \/  |/ _ _   _|_   _|   |  \/  | ___  _ __   __ _  ___
| |\/| | | | || |   | |_____| |\/| |/ _ | '_ \ / _` |/ _ \
| |  | | |_| || |   | |_____| |  | | (_) | | | | (_| | (_) |
|_|  |_|___|_|   |_|     |_|  |_|_**/|_| |_|\**, |_**/
                                                |_**/

Exception in thread "main" java.lang.IllegalArgumentException: no matching constructor found on class com.sandinh.paho.akka.MqttPubSub for arguments [class com.sandinh.paho.akka.MqttPubSub$PSConfig, class java.lang.String]
    at akka.util.Reflect$.error$1(Reflect.scala:82)
    at akka.util.Reflect$.findConstructor(Reflect.scala:106)
    at akka.actor.ArgsReflectConstructor.<init>(Props.scala:350)
    at akka.actor.IndirectActorProducer$.apply(Props.scala:309)
    at akka.actor.Props.producer(Props.scala:176)
    at akka.actor.Props.<init>(Props.scala:189)
    at akka.actor.Props$.apply(Props.scala:93)
    at com.izmailoff.mm.mqtt.MqttIntermediary$class.startMqttIntermediary(MqttIntermediary.scala:15)
    at com.izmailoff.mm.service.Boot$.startMqttIntermediary(Boot.scala:7)
    at com.izmailoff.mm.service.Boot$.delayedEndpoint$com$izmailoff$mm$service$Boot$1(Boot.scala:27)
    at com.izmailoff.mm.service.Boot$delayedInit$body.apply(Boot.scala:8)
    at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
    at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.App$$anonfun$main$1.apply(App.scala:76)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
    at scala.App$class.main(App.scala:76)
    at com.izmailoff.mm.service.Boot$.main(Boot.scala:7)
    at com.izmailoff.mm.service.Boot.main(Boot.scala)

How can I resolve this please?

Regards,
Supun

**Comment by izmailoff** [comment]
I'm getting the same error now. Seems like something has changed in the library (constructor signature). Will try to fix now.

**Comment by izmailoff** [comment]
It was a problem with Actor constructor not being called properly and failing at runtime due to reflection. Should be fixed now. Thanks for reporting the problem!

**Comment by IrangaSupunAthukorale** [comment]
Thank you very much for lookong into this.
